name: WatchVuln Monitor

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Sync fork with upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: zema1/watchvuln
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build WatchVuln binary
        run: |
          go mod download
          CGO_ENABLED=1 go build -ldflags "-s -w" -o watchvuln main.go

      - name: Check if database exists
        id: check_db
        run: |
          if [ -f "vuln_v3.sqlite3" ]; then
            echo "db_exists=true" >> $GITHUB_OUTPUT
          else
            echo "db_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Run WatchVuln (First time)
        if: steps.check_db.outputs.db_exists == 'false'
        timeout-minutes: 20
        run: |
          ./watchvuln --db sqlite3://vuln_v3.sqlite3 --dt ${{ secrets.DINGDING_TOKEN }} --ds ${{ secrets.DINGDING_SECRET }}

      - name: Run WatchVuln (Subsequent runs)
        if: steps.check_db.outputs.db_exists == 'true'
        run: |
          ./watchvuln --db sqlite3://vuln_v3.sqlite3 --dt ${{ secrets.DINGDING_TOKEN }} --ds ${{ secrets.DINGDING_SECRET }} --diff

      - name: Commit database changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add vuln_v3.sqlite3
          git diff --staged --quiet || git commit -m "Update vulnerability database [$(date +'%Y-%m-%d %H:%M:%S')]"
          git push
